spring:
  redis:
    host: 192.168.99.100
    port: 6379
    database: 1
  jpa:
    hibernate:
      ddl-auto: create #自动更新
    show-sql: true  #日志中显示sql语句
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
#debug: true
#  日志级别从低到高分为TRACE < DEBUG < INFO < WARN < ERROR < FATAL，如果设置为WARN，则低于WARN的信息都不会输出。
#  logging.level.com.dudu=DEBUG：com.dudu包下所有class以DEBUG级别输出
#  logging.level.root=WARN：root日志以WARN级别输出
logging:
  file: ./log/default.log
  ##test test11
mybatis:
  mapper-locations: /mybatis/*.xml

db:
  mysql:
    url: jdbc:mysql://192.168.99.100:3306/tmemp?useSSL=false
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver