spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:32779/tsy_cms?useSSL=false&serverTimezone=UTC
    username: hailong
    password: hailong
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
debug: true

##test test11