spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://192.168.99.100:3306/temp?useSSL=false
  redis:
    host: 192.168.99.100
    port: 6379
    database: 1
  jpa:
    hibernate:
      ddl-auto: update #自动更新
    show-sql: true  #日志中显示sql语句
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

#debug: true
#  日志级别从低到高分为TRACE < DEBUG < INFO < WARN < ERROR < FATAL，如果设置为WARN，则低于WARN的信息都不会输出。
#  logging.level.com.dudu=DEBUG：com.dudu包下所有class以DEBUG级别输出
#  logging.level.root=WARN：root日志以WARN级别输出
logging:
  file: ./log/default.log
  ##test test11
mybatis:
  #实体类所做包
  type-aliases-package: com.hailong.jpafortsy.dbmodel
  mapper-locations: classpath:mybatis/*.xml
#db:
#  mysql:
#    jdbcUrl: jdbc:mysql://192.168.99.100:3306/temp?useSSL=false
#    user: root
#    password: 1234
#    driverClass: com.mysql.jdbc.Driver
#    maxIdleTime: 60
#    initialPoolSize: 8
#    minPoolSize: 5
#    maxPoolSize: 10
  